version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: manchester
      POSTGRES_DB: larasubnet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: larasubnetv2-app
    container_name: larasubnetv2-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    depends_on:
      db:
        condition: service_healthy
    environment:
      # pastikan .env ada di project root; bisa override jika perlu
      APP_ENV: production
    entrypoint: ["/var/www/docker-entrypoint.sh"]

  webserver:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  pgdata:
